name: pull request check workflow

on:
   pull_request:
           branches:
                   - main

jobs:
    pr_check:
       runs-on: ubuntu-latest
       steps:
       - name: checkout repository
         uses: actions/checkout@v2
       - name: Set up Node JS
         uses: actions/setup-node@v2
         with:
           node-version: 14.x
           cache: npm
       - name: Install
         run: npm ci
       - name: Test
         run: npm test
       - name: Validate Template
         uses: hashicorp/packer-github-actions@master
         with:
           command: validate
           arguments: -syntax-only
           target: ami.json
